# Generated by Django 4.1.2 on 2022-10-17 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movie', to='movie_app.movie'),
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
