# Generated by Django 4.1.2 on 2022-10-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_remove_movie_movie_review_movie_reviewa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='reviewa',
            new_name='reviews',
        ),
    ]
