# Generated by Django 4.1.2 on 2022-10-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_rename_reviewa_movie_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='descrtiption',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
